apiVersion: v1
kind: ServiceAccount
metadata:
  name: container-pulse-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: container-pulse-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: container-pulse-binding
subjects:
  - kind: ServiceAccount
    name: container-pulse-monitor
    namespace: default
roleRef:
  kind: ClusterRole
  name: container-pulse-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      serviceAccountName: container-pulse-monitor
      containers:
        - name: monitor
          image: container-pulse-monitor:latest
          imagePullPolicy: Never
          env:
            - name: MODE
              value: "kubernetes"
            - name: MONITORED_NAMESPACES
              value: "default"
            - name: SLACK_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: container-pulse-secrets
                  key: SLACK_WEBHOOK
                  optional: true
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: container-pulse-secrets
                  key: SMTP_HOST
                  optional: true
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: container-pulse-secrets
                  key: SMTP_PORT
                  optional: true
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: container-pulse-secrets
                  key: SMTP_USER
                  optional: true
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: container-pulse-secrets
                  key: SMTP_PASSWORD
                  optional: true
            - name: ALERT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: container-pulse-secrets
                  key: ALERT_EMAIL
                  optional: true
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          ports:
            - containerPort: 8000
      volumes:
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: monitor
spec:
  selector:
    app: monitor
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
